let div=document.createElement("div")
let h1=document.createElement('h1')
let text=document.createTextNode("This is a heading")
let p=document.createElement('p')
let textNode=document.createTextNode("This is a P tag")
let button=document.createElement('button')
let textNode2=document.createTextNode("Click Here")
div.appendChild(h1)
h1.appendChild(text)
div.appendChild(p)
p.appendChild(textNode)
div.appendChild(button)
button.appendChild(textNode2)
console.log(div);
